-- ============================================================
-- 五行纳音 · 有缘人匹配池 —— Supabase 数据库初始化脚本
-- ============================================================
-- 使用方法：
--   1. 登录 https://supabase.com 创建免费项目
--   2. 左侧 SQL Editor → 粘贴本文件全部内容 → Run
--   3. Authentication → Providers → Email：
--      关闭「Confirm email」（演示用，注册后免邮箱验证即可登录）
--   4. Project Settings → API：复制 Project URL 和 anon public key，
--      填入应用「匹配池 → ☁️ 云端」设置面板
-- ============================================================

-- ---------- 用户扩展档案（登录后保存测试结果，跨设备恢复） ----------
create table if not exists profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  name        text not null default '无名之辈',
  gender      text default 'secret',
  age         int,
  seek_gender text default 'any',
  tags        jsonb default '[]',
  tagline     text default '',
  drink       text,
  drink_id    text,
  nayin       text,
  dominant    text,
  scores      jsonb default '{}',
  temp        text,
  bubble      text,
  pref        text default 'friend',
  updated_at  timestamptz default now()
);

-- ---------- 匹配池（在池中的用户） ----------
create table if not exists pool (
  uid         uuid primary key references auth.users(id) on delete cascade,
  state       text default 'waiting',            -- waiting | matched | idle
  match_id    text,
  name        text,
  gender      text default 'secret',
  age         int,
  seek_gender text default 'any',
  tags        jsonb default '[]',
  tagline     text default '',
  pref        text default 'friend',
  drink       text,
  nayin       text,
  dominant    text,
  scores      jsonb default '{}',
  temp        text,
  bubble      text,
  joined_at   timestamptz default now()
);

-- ---------- 匹配记录 ----------
create table if not exists matches (
  id         text primary key,
  a_uid      uuid,
  b_uid      uuid,
  score      int,
  relation   jsonb default '{}',                 -- {type, label}
  reasons    jsonb default '[]',
  created_at timestamptz default now(),
  ended_at   timestamptz,
  ended_by   uuid,
  seen       jsonb default '{}'
);

-- ---------- 聊天消息 ----------
create table if not exists messages (
  id          bigint generated by default as identity primary key,
  match_id    text not null,
  sender      uuid not null,
  sender_name text,
  text        text not null,
  at          timestamptz default now()
);
create index if not exists messages_match_idx on messages(match_id, at);

-- ---------- 社区帖子 / 评论 ----------
create table if not exists posts (
  id       text primary key,
  channel  text not null,                        -- wood/fire/earth/metal/water
  uid      uuid,
  name     text,
  gender   text default 'secret',
  age      int,
  drink    text,
  dominant text,
  tags     jsonb default '[]',
  text     text not null,
  at       timestamptz default now(),
  likes    jsonb default '[]'
);
create table if not exists comments (
  id       text primary key,
  post_id  text references posts(id) on delete cascade,
  uid      uuid,
  name     text,
  dominant text,
  text     text not null,
  at       timestamptz default now()
);
create index if not exists comments_post_idx on comments(post_id);

-- ============================================================
-- 行级安全（RLS）：登录用户可读写；只能改自己的数据
-- ============================================================
alter table profiles enable row level security;
alter table pool     enable row level security;
alter table matches  enable row level security;
alter table messages enable row level security;
alter table posts    enable row level security;
alter table comments enable row level security;

create policy "profiles read"   on profiles for select to authenticated using (true);
create policy "profiles insert" on profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles update" on profiles for update to authenticated using (id = auth.uid());

create policy "pool read"   on pool for select to authenticated using (true);
create policy "pool write"  on pool    for insert to authenticated with check (uid = auth.uid());
create policy "pool update" on pool    for update to authenticated using (uid = auth.uid());
create policy "pool delete" on pool    for delete to authenticated using (uid = auth.uid());

create policy "matches read"   on matches for select to authenticated
  using (a_uid = auth.uid() or b_uid = auth.uid());
create policy "matches update" on matches for update to authenticated
  using (a_uid = auth.uid() or b_uid = auth.uid());

create policy "messages read"   on messages for select to authenticated using (true);
create policy "messages insert" on messages for insert to authenticated with check (sender = auth.uid());

create policy "posts read"   on posts for select to authenticated using (true);
create policy "posts insert" on posts for insert to authenticated with check (uid = auth.uid());
create policy "posts update" on posts for update to authenticated using (true);   -- 点赞

create policy "comments read"   on comments for select to authenticated using (true);
create policy "comments insert" on comments for insert to authenticated with check (uid = auth.uid());

-- ============================================================
-- 五行生克辅助函数
-- ============================================================
create or replace function sheng(el text) returns text language sql immutable as $$
  select case el when 'wood' then 'fire' when 'fire' then 'earth' when 'earth' then 'metal'
                 when 'metal' then 'water' when 'water' then 'wood' end
$$;

create or replace function ke(el text) returns text language sql immutable as $$
  select case el when 'wood' then 'earth' when 'earth' then 'water' when 'water' then 'fire'
                 when 'fire' then 'metal' when 'metal' then 'wood' end
$$;

create or replace function el_cn(el text) returns text language sql immutable as $$
  select case el when 'wood' then '木' when 'fire' then '火' when 'earth' then '土'
                 when 'metal' then '金' when 'water' then '水' end
$$;

create or replace function gender_ok(seek text, target text) returns boolean language sql immutable as $$
  select seek = 'any' or target = 'secret' or seek = target
$$;

create or replace function rel_label(da text, db text) returns text language sql immutable as $$
  select case when da = db then el_cn(da) || el_cn(db) || '同气 · 同气相求'
              when sheng(da) = db then el_cn(da) || '生' || el_cn(db) || ' · 五行相生'
              when sheng(db) = da then el_cn(db) || '生' || el_cn(da) || ' · 五行相生'
              when ke(da) = db then el_cn(da) || '克' || el_cn(db) || ' · 相克制衡'
              else el_cn(db) || '克' || el_cn(da) || ' · 相克制衡' end
$$;

create or replace function pref_cn(p text) returns text language sql immutable as $$
  select case p when 'friend' then '朋友' when 'study' then '学习搭子'
                when 'meal' then '饭搭子' when 'suiyuan' then '随缘' else '朋友' end
$$;

-- ============================================================
-- 服务端匹配撮合（客户端每 4 秒 RPC 调用一次）
-- 与前端 pairScore 同一套算法：≥76 分配对，贪心撮合
-- ============================================================
create or replace function try_match() returns int
language plpgsql security definer set search_path = public as $$
declare
  v_count int := 0;
  r pool%rowtype;
  p pool%rowtype;
  v_best pool%rowtype;
  v_best_score int;
  v_score int;
  v_shared int;
  v_mid text;
  v_reasons jsonb;
begin
  for r in select * from pool where state = 'waiting' order by joined_at asc loop
    v_best_score := -1;
    for p in select * from pool where state = 'waiting' and uid <> r.uid loop
      continue when not gender_ok(r.seek_gender, p.gender) or not gender_ok(p.seek_gender, r.gender);

      v_score := 55;
      if r.dominant = p.dominant then v_score := v_score + 20;
      elsif sheng(r.dominant) = p.dominant then v_score := v_score + 28;
      elsif sheng(p.dominant) = r.dominant then v_score := v_score + 26;
      elsif ke(r.dominant) = p.dominant then v_score := v_score + 8;
      else v_score := v_score + 10;
      end if;

      if r.pref = 'suiyuan' and p.pref = 'suiyuan' then v_score := v_score + 9;
      elsif r.pref = p.pref then v_score := v_score + 10;
      elsif r.pref = 'suiyuan' or p.pref = 'suiyuan' then v_score := v_score + 6;
      else v_score := v_score + 2;
      end if;

      if r.seek_gender <> 'any' and p.gender <> 'secret' and r.seek_gender = p.gender then v_score := v_score + 6; end if;
      if p.seek_gender <> 'any' and r.gender <> 'secret' and p.seek_gender = r.gender then v_score := v_score + 6; end if;

      select count(*) into v_shared
        from jsonb_array_elements_text(coalesce(r.tags, '[]')) t
        where t.value::text in (select x::text from jsonb_array_elements_text(coalesce(p.tags, '[]')) x);
      v_score := v_score + least(12, v_shared * 4);

      if (r.temp = '温热' and p.temp = '清冷') or (r.temp = '清冷' and p.temp = '温热') then v_score := v_score + 5;
      elsif r.temp = p.temp then v_score := v_score + 2;
      end if;
      if coalesce(r.bubble, '') = coalesce(p.bubble, '') and r.bubble is not null then v_score := v_score + 2; end if;

      v_score := least(99, v_score);
      if v_score >= 76 and v_score > v_best_score then
        v_best_score := v_score;
        v_best := p;
      end if;
    end loop;

    if v_best.uid is not null then
      select jsonb_build_array(
        '五行关系：' || rel_label(r.dominant, v_best.dominant),
        case when r.pref = v_best.pref then '都在找「' || pref_cn(r.pref) || '」，心意一致' else '偏好不同，靠五行缘分补足' end,
        case when v_shared > 0 then '共同爱好，话题不愁' else null end
      ) - 'null'::jsonb into v_reasons;

      v_mid := 'm' || (floor(extract(epoch from clock_timestamp()) * 1000))::text || substr(md5(random()::text), 1, 6);
      insert into matches (id, a_uid, b_uid, score, relation, reasons, created_at)
      values (v_mid, r.uid, v_best.uid, v_best_score,
              jsonb_build_object('type',
                case when r.dominant = v_best.dominant then 'tong'
                     when sheng(r.dominant) = v_best.dominant or sheng(v_best.dominant) = r.dominant then 'sheng'
                     else 'ke' end,
                'label', rel_label(r.dominant, v_best.dominant)),
              v_reasons, now());
      update pool set state = 'matched', match_id = v_mid where uid in (r.uid, v_best.uid);
      v_count := v_count + 1;
    end if;
  end loop;
  return v_count;
end $$;

-- ============================================================
-- 结束聊天（任一方可结束，双方状态同步）
-- ============================================================
create or replace function end_match(p_match_id text) returns void
language plpgsql security definer set search_path = public as $$
declare
  m matches%rowtype;
begin
  select * into m from matches where id = p_match_id and ended_at is null
    and (a_uid = auth.uid() or b_uid = auth.uid());
  if m.id is null then return; end if;
  update matches set ended_at = now(), ended_by = auth.uid() where id = m.id;
  update pool set state = 'idle', match_id = null where uid in (m.a_uid, m.b_uid);
end $$;

-- ============================================================
-- 开启实时推送（Realtime）
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array['pool','matches','messages','posts','comments'] loop
    begin
      execute format('alter publication supabase_realtime add table %I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;
